typography_spectrum: 0.8165275377687067
color:
  brandColors:
    - '#00585F'
    - '#009393'
    - '#FFFCC4'
    - '#F0EDBB'
    - '#FF3800'
  brandStrength: 0.954353088978678
  lightness: 0.07766699674539268
  saturation: 0.3277254013810307
  rhythmicContrast: 0.686994442017749
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8136865973938257
analytics:
  google: null
  facebook: null
  twitter: null
name: best
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
